[package]
name = "polkadot-cli"
version = "0.9.12"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Polkadot Relay-chain Client Node"
edition = "2018"

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on Linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4.13"
thiserror = "1.0.30"
structopt = { version = "0.3.23", optional = true }
futures = "0.3.17"

service = { package = "polkadot-service", path = "../node/service", default-features = false, optional = true }
polkadot-node-core-pvf = { path = "../node/core/pvf", optional = true }

sp-core = { git = "https://github.com/AXIA-DEV/axlib-axtend", branch = "master" }
frame-benchmarking-cli = { git = "https://github.com/AXIA-DEV/axlib-axtend", optional = true , branch = "master" }
try-runtime-cli = { git = "https://github.com/AXIA-DEV/axlib-axtend", optional = true , branch = "master" }
sc-cli = { git = "https://github.com/AXIA-DEV/axlib-axtend", optional = true , branch = "master" }
sc-service = { git = "https://github.com/AXIA-DEV/axlib-axtend", optional = true , branch = "master" }

# this crate is used only to enable `trie-memory-tracker` feature
# see https://github.com/paritytech/axlib/pull/6745
sp-trie = { git = "https://github.com/AXIA-DEV/axlib-axtend", default-features = false , branch = "master" }

[build-dependencies]
axlib-build-script-utils = { git = "https://github.com/AXIA-DEV/axlib-axtend", branch = "master" }

[features]
default = [ "wasmtime", "db", "cli", "full-node", "trie-memory-tracker", "polkadot-native" ]
wasmtime = [ "sc-cli/wasmtime" ]
db = [ "service/db" ]
cli = [
	"structopt",
	"sc-cli",
	"sc-service",
	"frame-benchmarking-cli",
	"try-runtime-cli",
	"polkadot-node-core-pvf",
]
runtime-benchmarks = [ "service/runtime-benchmarks" ]
trie-memory-tracker = [ "sp-trie/memory-tracker" ]
full-node = [ "service/full-node" ]
try-runtime = [ "service/try-runtime" ]

# Configure the native runtimes to use. Polkadot is enabled by default.
#
# Validators require the native runtime currently
polkadot-native = [ "service/polkadot-native" ]
axctest-native = [ "service/axctest-native" ]
westend-native = [ "service/westend-native" ]
rococo-native = [ "service/rococo-native" ]

malus = [ "full-node", "service/malus" ]
disputes = [ "service/disputes" ]
