{
 "title": "Alphanet to Millau Header Sync Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Difference Between Source and Target Headers",
   "type": "graph",
   "description": "Shows how many headers behind the target chain is from the source chain.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(Westend_to_Millau_Sync_best_block_numbers{node=\"source\"}) - max(Westend_to_Millau_Sync_best_block_numbers{node=\"target\"})"
    }
   ]
  },
  {
   "title": "Headers Synced on Millau (Last 2 Mins)",
   "type": "graph",
   "description": "How many headers has the relay synced from the source node in the last 2 mins?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(Westend_to_Millau_Sync_best_block_numbers{node=\"source\"}[2m])-min_over_time(Westend_to_Millau_Sync_best_block_numbers{node=\"source\"}[2m])",
     "legendFormat": "Number of new Headers on Alphanet (Last 2 Mins)"
    }
   ]
  },
  {
   "title": "Best Blocks according to Relay",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Westend_to_Millau_Sync_best_block_numbers",
     "legendFormat": "Best Known Header on {{node}} Node"
    }
   ]
  },
  {
   "title": "Average System Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Westend_to_Millau_Sync_system_average_load",
     "legendFormat": "Average system load in last {{over}}"
    }
   ]
  },
  {
   "title": "Relay Process CPU Usage ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(Westend_to_Millau_Sync_process_cpu_usage_percentage[1m])",
     "legendFormat": "1 CPU = 100"
    }
   ]
  },
  {
   "title": "Queued Headers in Relay",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Westend_to_Millau_Sync_blocks_in_state",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Memory Usage for Relay Process",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Westend_to_Millau_Sync_process_memory_usage_bytes / 1024 / 1024",
     "legendFormat": "Process memory, MB"
    }
   ]
  }
 ]
}