name: Send new release notification to matrix channels
on:
  release:
    types:
      - published
jobs:
  ping_matrix:
    strategy:
      matrix:
        channel:
        - '!LhjZccBOqFNYKLdmbb:axia.builders' # #AxiaTestValidatorLounge:axia.builders
        - '!FMwxpQnYhRCNDRsYGI:matrix.parity.io' # #axctest-announcements:matrix.parity.io
        - '!NZrbtteFeqYKCUGQtr:matrix.parity.io' # #axiavalidatorlounge:web3.foundation
        - '!UqHPWiCBGZWxrmYBkF:matrix.parity.io' # #axia-announcements:matrix.parity.io
        - '!NTogofoetwjbTwOoPi:matrix.parity.io' # Internal release-notes channel
    runs-on: ubuntu-latest
    steps:
      - uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ matrix.channel }} # heh
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          message: "***Axia ${{github.event.release.tag_name}} has been released!***<br/>${{github.event.release.html_url}}<br/><br/>${{github.event.release.body}}<br/>"
          server: "matrix.parity.io"
